import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/adminSidebar/AdminSidebar";
import AdminHeader from "@/components/adminHeader/adminHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <AdminSidebar />
        <main className="flex flex-col w-full">
          <AdminHeader />
          {children}
        </main>
      </SidebarProvider>
    </> 
  );
}
