import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/adminSidebar/AdminSidebar";
import AdminHeader from "@/components/adminHeader/AdminHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <AdminSidebar />
        <main className="flex flex-col w-full items-center justify-start">
          <AdminHeader />
          {children}
        </main>
      </SidebarProvider>
    </>
  );
}
